name: 04 - Using Actions
on:
  push:

jobs:
  build :
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        run: github/checkout@v2
      - name: Printing Folders
        run: ls -R
  mac:
    name: mac-echo
    runs-on: macos-latest
    steps:
      - name: Show OS
        run: |
          echo "This job is running on a MacOS runner."
          echo "${{ runner.os }}"