name: 04 - Using Actions
on:
  push:

jobs:
  build :
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install Dependencies
        run: |
            cd 04-using-actions/react-app
            npm ci
      - name: Run Unit Tests
        run: |
          cd 04-using-actions/react-app
          npm run test