name: 11 - Working with Inputs
run-name: "11 - Working with Inputs"

on:
  pull_request:
    branches:
      - salmon
  workflow_dispatch:
    inputs:
      dry-run:
        description: "Skip deployment and only print build output"
        type: "boolean"
        default: false
      target:
        description: "Which environment the workflow will target"
        type: environment
        required: true
      tag:
        description: "Release from which to build and deploy"
        type: choice
        options:
          - "v1"
          - "v2"
          - "v3"
        required: false
        default: "v3"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Build"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ !inputs.dry-run }}
    environment: ${{ inputs.target }}
    steps:
      - name: 'Deploy'
        run: echo "Deploying to ${{ inputs.target }}"