name: 12 - Working with Outputs
run-name: "12 - Working with Outputs"

on:
  pull_request:
    branches:
      - salmon
  workflow_dispatch:
    inputs:
      build-status:
        description: "Build status"
        type: choice
        options:
          - "success"
          - "failure"
        required: false
        default: "success"

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
        status: ${{ steps.build.outputs.status }}
    steps:
      - name: Print GITHUB_OUTPUT path
        run: echo "$GITHUB_OUTPUT"
      - name: Build
        id: build
        run: |
            echo "status=${{ inputs.build-status }}" >> $GITHUB_OUTPUT

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ needs.build.outputs.status == 'success' }}
    steps:
      - name: 'Deploy'
        run: echo "Deploying"