name: 14 - Working with Artifacts
run-name: "14 - Working with Artifacts"

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Name of the app"
        type: string
        required: false
        default: "app"
      path:
        description: "Path to the app"
        type: string
        required: false
        default: "14-artifacts/react-app/build"

jobs:
  test-build:
    runs-on: ubuntu-latest
    needs: install-deps
    defaults:
      run:
        working-directory: 14-artifacts/react-app
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "20.x"

      - name: Download cached dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: 14-artifacts/react-app/node_modules
          key: deps-node-modules-${{ hashFiles('14-artifacts/react-app/package-lock.json') }}

      - name: Install dependencies
        if: ${{ needs.cache.outputs.cache-hit == 'true' }}
        run: npm ci

      - name: Unit tests
        run: npm run test

      - name: Build code
        run: npm run build

      - name: Upload build files
        uses: actions/upload-artifact@v4
        with:
          name: react-app-build
          path: 14-artifacts/react-app/build

  install-deps:
    outputs:
      deps-cache-key: ${{ steps.cache-key.outputs.cache-key }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 14-caching/react-app
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ inputs.node-version }}

      - name: Calculate cache key
        id: cache-key
        run: |
          echo "cache-key=deps-node-modules-${{ hashFiles('14-caching/react-app/package-lock.json') }}" >> $GITHUB_OUTPUT
      
      - name: Download cached dependencies
        if: ${{ steps.cache-key.outputs.cache-key }}
        uses: actions/cache@v3
        with:
          path: 14-caching/react-app/node_modules
          key: ${{ steps.cache-key.outputs.cache-key }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Unit tests
        run: npm run test

      - name: Build code
        run: npm run build

      - name: Upload build files
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.name }}-build
          path: '${{ inputs.path }}/'

  linting:
    outputs:
      deps-cache-key: ${{ steps.cache-key.outputs.cache-key }}
    runs-on: ubuntu-latest
    needs: install-deps
    defaults:
      run:
        working-directory: 13-caching/react-app
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ inputs.node-version }}

      - name: Download cached dependencies
        if: ${{ needs.install-deps.outputs.deps-cache-key }}
        uses: actions/cache@v3
        with:
          path: 13-caching/react-app/node_modules
          key: ${{ needs.install-deps.outputs.deps-cache-key }}

      - name: Testing
        run: npm run test

      - name: Linting
        run: echo "Linting..."

  deploy:
    needs: test-build
    runs-on: ubuntu-latest
    steps:
      - name: Download build files
        uses: actions/download-artifact@v5
        with:
          name: ${{ inputs.name }}-build
          path: ${{ inputs.path }}
    
      - name: Show folder structure
        run: ls -R

